### ISSUE TITLE
fixes for Bootstrap3 LESS variables and methods

### ISSUE THREAD

**Issue by witzawitz** [uxsolutions/bootstrap-datepicker#570]
That worked for me.

``` less
.border-radius(@radius)
{
    .border-top-radius(@radius);
    .border-bottom-radius(@radius);
}
.buttonBackground (@start, @end)
{
    background: @start;
}
@baseLineHeight : @line-height-base;
@btnPrimaryBackground : @btn-primary-bg;
@grayLight : @gray-light;
@grayLighter : @gray-lighter;
@orange : @brand-warning;
@white : #fff;
```
